dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh | bash
notifications:
  slack:
    rooms:
      secure: KCOUYhoj3CmieQooHwMKSils1fxDszFkuZCjofl1rpDefm4EV1AT5Uvtgsa9QjFg/RteMtw7k1k6LbUUyB2C2fk8VqfbogP6uA1MXdPNel0O45oI2zjVBBsVtOYAMRrcrN8U0S7nbcxy7BFIvLQNxLGbbaqV67O2guEuuh3HKYrztbgsOiQGxBKOM1XBMgOb7Z8eZ+vh3eSDGXWglIkWyFqTdgdU/53ro4R9b6rX/hgFkkBkhYfK+1t+/TcbBk5ISAq9hWwmPFPHSYe75pvBezvTPUV9SKy4Qi4mqXrk7IkrA2+Iaae/Fvi2xdUeRo+SgqZGBjOnlLpzBjqpdekaF27m9nGstMe9JhGJBF4nCAFFBYncR9RZfntZ+hZc3fJ9UURItC5qq+ThXqCptL7xduulNP5a8ErowBBOcDFE6jioofywHgKgMpDM/cEb9ZaQTCM2IopsnAuGP049T4Kkf9If4Id/afCy5QVtzicmhg94jdnmO796qDh+1Z9mN30K0Dia0x335Nr3Du5Jg466kBmgZFjVuY4x7PvLYReWEoHu38hrAr6enxYgeM4N27mw9YpnT31ux2T9ICLGR9OE4nR7TuMyf4oCakebIKmaDyrrQn+sihzv7edPp23lJ2aNvg4iAuErNpEIPLiPPRlEMk9LvSpMmizinvHWrs/gULw=
