comment:
  image:
    repository: nicecontrol/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: nicecontrol/post
    tag: latest
  service:
      externalPort: 5000

ui:
  image:
    repository: nicecontrol/ui
    tag: latest
  service:
      externalPort: 9292
