global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#anton_sukhobochenko'
