version: '3.3'
services:
  post_db:
    image: mongo:${VERSION_MONGO}
    volumes:
      - post_db:/data/db
    networks:
      home_net:
        aliases:
          - post_db
          - comment_db
  
  ui:
    image: ${USERNAME}/ui:${VERSION_UI}
    ports:
      - ${PORTS}:${PORTS}/tcp
    networks:
      - home_net
  post:
    image: ${USERNAME}/post:${VERSION_POST}
    networks:
      - home_net
  comment:
    image: ${USERNAME}/comment:${VERSION_COMMENT}
    networks:
      - home_net
volumes:
  post_db: 


networks:
  home_net:


