version: '3.3'
services:
  post_db:
    image: mongo:${VERSION_MONGO}
    volumes:
      - post_db:/data/db
    networks:
      home_net:
        aliases:
          - post_db
          - comment_db
  
  ui:
    image: ${USERNAME}/ui:${VERSION_UI}
    ports:
      - ${PORTS}:${PORTS}/tcp
    networks:
      - home_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  post:
    image: ${USERNAME}/post:${VERSION_POST}
    networks:
      - home_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  comment:
    image: ${USERNAME}/comment:${VERSION_COMMENT}
    networks:
      - home_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
volumes:
  post_db: 


networks:
  home_net:


