---
  - name: Gitlab Runner launcher
    hosts: gitlab_ci
    become: true
    gather_facts: False

    tasks:
      - name: Launch container with Runner
        docker_container:
          name: gitlab-runner
          image: gitlab/gitlab-runner:latest
          state: started
          restart: yes
          restart_policy: always
          volumes:
            - /srv/gitlab-runner/config:/etc/gitlab-runner
            - /var/run/docker.sock:/var/run/docker.sock
      
      - name: Gitlab Runner Register
      - raw: docker exec -it gitlab-runner gitlab-runner register \
             --non-interactive --executor "docker" \
             --docker-image alpine:latest --url "http://35.189.228.73" \ 
             --registration-token "3c5qn5ooUZAKtkbD_HTv" --description "my-runner-2" \
             --tag-list "linux,xenial,ubuntu,docker" --run-untagged \
             --locked="false"